// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXISxPmvFV2wD73JGLkgqWz38PdGjOlc',
    appId: '1:1064680055657:web:b3b19ee8def721ad6353f8',
    messagingSenderId: '1064680055657',
    projectId: 'bacaansholat-d8a72',
    authDomain: 'bacaansholat-d8a72.firebaseapp.com',
    storageBucket: 'bacaansholat-d8a72.appspot.com',
    measurementId: 'G-4X97NZGH8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVyIXqgplHu2WQfKNjB1b9VIQcEbvdbg',
    appId: '1:1064680055657:android:a77f2788d566a2c16353f8',
    messagingSenderId: '1064680055657',
    projectId: 'bacaansholat-d8a72',
    storageBucket: 'bacaansholat-d8a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tZiaFmqAHUeJmR6TQH-1u2UkCWAnvhs',
    appId: '1:1064680055657:ios:86a5cfa5edc744756353f8',
    messagingSenderId: '1064680055657',
    projectId: 'bacaansholat-d8a72',
    storageBucket: 'bacaansholat-d8a72.appspot.com',
    iosBundleId: 'com.example.bacaanSholat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0tZiaFmqAHUeJmR6TQH-1u2UkCWAnvhs',
    appId: '1:1064680055657:ios:eeb6ef5153cdc32d6353f8',
    messagingSenderId: '1064680055657',
    projectId: 'bacaansholat-d8a72',
    storageBucket: 'bacaansholat-d8a72.appspot.com',
    iosBundleId: 'com.example.bacaanSholat.RunnerTests',
  );
}
